a=int(input("numarul de oua care  face prima gaina intr-o zi ="))
b=int(input("numarul de oua care  face a doua gaina intr-o zi ="))
c=int(input("numarul de oua care  face a treia gaina intr-o zi ="))
d=int(input("numarul de oua care  face a patra gaina intr-o zi ="))
print("intr-o saptamina gainile vor face  ",7*(a+b+c+d)," de oua")